# DVC data processing pipeline
vars:
- DATA_DIR: data
- MODEL_DIR: model
- NAVEC_PATH: data/navec_hudlit_v1_12B_500K_300d_100q.tar
- SAFE_DICT_PATH: data/safe.txt
- NOT_SAFE_DICT_PATH: data/not-safe.txt
- WIKI_DATA_PATH: data/ruwiki-latest-pages-articles.xml.bz2
- SEGM_DATA_PATH: data/ruwiki-yo-segments.txt
- VOCAB_FILENAME: vocab.txt
- MARKUPS_FILENAME: markups.jsonl.bz2
- CONFIG_PATH: params.yaml
- METRICS_PATH: reports/metrics.json
stages:
  download-ruwiki:
    cmd: scripts/download_russian_wiki_dump.sh
    deps:
    - scripts/download_russian_wiki_dump.sh
    outs:
    - ${WIKI_DATA_PATH}
  download-eyo-dicts:
    cmd: scripts/download_eyo_kernel_dicts.sh
    deps:
      - scripts/download_eyo_kernel_dicts.sh
    outs:
    - ${SAFE_DICT_PATH}
    - ${NOT_SAFE_DICT_PATH}
  download-pretrained-embeddings:
    cmd: scripts/download_pretrained_embeddings.sh
    deps:
    - scripts/download_pretrained_embeddings.sh
    outs:
    - ${NAVEC_PATH}
  extract-segments-from-wiki:
    cmd: >-
      python -m scripts.extract_segments_from_wiki
      ${data.extract}
      -i ${WIKI_DATA_PATH}
      -o ${SEGM_DATA_PATH}
    deps:
<<<<<<< HEAD
    - ${WIKI_DATA_PATH}
=======
      - ${WIKI_DATA_PATH}
      - ${SAFE_DICT_PATH}
      - ${NOT_SAFE_DICT_PATH}
>>>>>>> ceca7db (update: fix eyo dictionaries versions, reproduce again, update dvc config and docs)
    outs:
    - ${SEGM_DATA_PATH}
  generate-dataset:
    cmd: >-
      python -m scripts.generate_dataset
      ${data.generate}
      --vocab-filename ${VOCAB_FILENAME}
      --markups-filename ${MARKUPS_FILENAME}
      -i ${SEGM_DATA_PATH}
      -O ${DATA_DIR}
    deps:
      - ${WIKI_DATA_PATH}
      - ${SEGM_DATA_PATH}
      - ${SAFE_DICT_PATH}
      - ${NOT_SAFE_DICT_PATH}
    outs:
    - ${DATA_DIR}/train-${MARKUPS_FILENAME}
    - ${DATA_DIR}/test-${MARKUPS_FILENAME}
    - ${DATA_DIR}/${VOCAB_FILENAME}
  train-model:
    cmd: >-
      python -m scripts.train_model
      ${model.train}
      --navec-path ${NAVEC_PATH}
      --vocab-path ${DATA_DIR}/${VOCAB_FILENAME}
      --train-markups-path ${DATA_DIR}/train-${MARKUPS_FILENAME}
      --test-markups-path ${DATA_DIR}/test-${MARKUPS_FILENAME}
    deps:
    - ${DATA_DIR}/train-${MARKUPS_FILENAME}
    - ${DATA_DIR}/test-${MARKUPS_FILENAME}
    - ${DATA_DIR}/${VOCAB_FILENAME}
    - ${NAVEC_PATH}
    outs:
    - ${MODEL_DIR}
  evaluate-model:
    cmd: >-
      python -m scripts.evaluate_model
      --config-path ${CONFIG_PATH}
      --markups-path ${DATA_DIR}/test-${MARKUPS_FILENAME}
      --vocab-path ${DATA_DIR}/${VOCAB_FILENAME}
      --save-path ${METRICS_PATH}
    deps:
    - ${DATA_DIR}/test-${MARKUPS_FILENAME}
    - ${DATA_DIR}/${VOCAB_FILENAME}
    - ${CONFIG_PATH}
    - ${MODEL_DIR}
    params:
    - model.name
    - model.params
    metrics:
    - ${METRICS_PATH}:
        cache: false
params:
- dvclive/params.yaml
artifacts:
  model:
    path: model/model.pt
    type: model
    desc: model checkpoint
  vocab:
    path: model/vocab.txt
    type: vocab
    desc: model vocab
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
- dvclive/plots/sklearn/test/pr_curve.json:
    template: simple
    x: recall
    y: precision
    title: Precision-Recall Curve
    x_label: Recall
    y_label: Precision
