[tool.pytest.ini_options]
pythonpath = '.'
testpaths = ['tests']
python_files = 'test_*.py'
addopts = '--strict-markers --disable-pytest-warnings'
disable_test_id_escaping_and_forfeit_all_rights_to_community_support = true

[tool.isort]
profile = 'google'
force_sort_within_sections = false
line_length = 100
lines_between_types = 1
lines_after_imports = 2
multi_line_output = 3
include_trailing_comma = true
virtual_env = 'venv'

[tool.docformatter]
recursive = true
pre-summary-space = false
wrap-descriptions = 80
wrap-summaries = 100
style = 'google'
blank = true

[tool.black]
line-length = 100
skip-string-normalization = true
include = '\.pyi?$'
exclude = '''
/(
    .eggs
    | .git
    | .hg
    | .mypy_cache
    | .tox
    | venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.mypy]
python_version = '3.9'
show_error_codes = true
no_implicit_optional = true

warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
warn_redundant_casts = true

check_untyped_defs = true
disallow_untyped_defs = true
disallow_any_unimported = true
no_namespace_packages = true

exclude = []

[[tool.mypy.overrides]]
module = [
    'razdel',
    'sklearn',
    'iterstrat.*',
    'corus.*',
    'navec',
    'dvclive',
]
ignore_missing_imports = true
